### ISSUE TITLE
Don’t load the extension

### ISSUE THREAD

**Issue by bepolymathe** [m0nk3h/protonvpn-mon-gse#1]
I followed the indicated procedure (and I even restarted the extensions and the computer) but I don't "see" the extension in gnome-tweak-tool ...
Any idea ?

Here gnome Version 3.34.4

**Comment by YarnSphere** [comment]
Had the same issue. It's because the README is wrong, the folder now has to be named `protonvpn-mon@butmonkeh` instead of `gnordvpn-local@isopolito`.

**Comment by bepolymathe** [comment]
And need to restart computer ?

**Comment by bepolymathe** [comment]
And need to restart computer... (in my case).
